### ISSUE TITLE
Unable to use local images in ImageDevContainer

### ISSUE THREAD

**Issue by prabhuteja12** [hide-org/hide#116]
Hello! 
I'm trying to use a local image that I built in the `ImageDevContainer` and I run into 

```
hide.client.hide_client.HideClientError: Failed to create project: Failed to launch devcontainer: Failed to pull or build image: Failed to pull image: Error response from daemon: pull access denied for pttest, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

I have verified that I am able to compose my own `Dockerfile` that uses this image and works as expected. 
One aspect I see is that the error doesn't contain the tag name, that is pull access is denied for __pttest__ but no tag. 

Is this intended behaviour?  What is the way to use local images with Hide?

Thank you!

**Comment by prabhuteja12** [comment]
Just tried manually composing a `.devcontainer.json` and letting VSCode do its thing, and that works. Does `hide` strip the tag details off? How do I provide that?

**Comment by aleh-null** [comment]
@prabhuteja12 Hi! Thanks for reporting. We will look into it.

**Comment by aleh-null** [comment]
@prabhuteja12 Hi, we just merged a [fix](https://github.com/hide-org/hide/pull/119). Let us know if it solved the issue.

**Comment by artmoskvin** [comment]
Just for transparency, the missing tag in the error message was a red herring. The real problem was `hide` not checking the local images at all which has been fixed by #119.

**Comment by prabhuteja12** [comment]
Just tried a local example, and it works.. Thank you very much for the fix!

**Comment by prabhuteja12** [comment]
I see that when I use a local image, there is an error with `LSP client not found languageId=unknown projectId=......`. But the `search_symbol` functionality still works. Is this just a bug with the logger?

**Comment by artmoskvin** [comment]
I guess the error refers to something different e.g. file read/write. As you said, if LSP client is not found, then the symbol search would not work. Could you check what the source of the log? it should be something like `pkg/lsp/service.go:...`

**Comment by prabhuteja12** [comment]
`WRN pkg/lsp/service.go:250 > LSP client not found languageId=unknown projectId=....`

This is what I see with the LSP.

**Comment by artmoskvin** [comment]
Noted. Anyway, I'll see if we can improve logging to avoid such confusions.
