### ISSUE TITLE
`run_task` as sudo

### ISSUE THREAD

**Issue by prabhuteja12** [hide-org/hide#148]
Hello!

I wanted to ask you why `Client.run_task` seems to run as root. 
`hc.run_task(project.id, command="whoami")` return `root`.

Also, the user with the ownership of the `/workspace` folder seems to be `24909395`. Can these be configured somehow?

Thank you!
Prabhu

**Comment by artmoskvin** [comment]
Hey Prabhu! By default, the container starts with the root user. You can override this with the `containerUser` parameter in the devcontainer config. See https://github.com/hide-org/hide-sdk/blob/32148230576b33d1200d4ade84dc2afea7a5c230/hide/devcontainer/model.py#L197

As for the /workspace folder, I need to check. I'm afk until Friday, so the soonest I can check is on the weekend.

**Comment by prabhuteja12** [comment]
Oh awesome! Thank you for clarifying!

**Comment by wistuba** [comment]
I think the real issue is when we start mixing `bash` commands with client's update file logic:

```
# Creates a new file with sudo rights
client.run_task(project.id, "touch dummy.txt")

# hide.client.hide_client.HideClientError: Failed to update file: Failed to write file dummy.txt: open /X/dummy.txt: permission denied
client.update_file(project.id, "dummy.txt", update=OverwriteUpdate(content="test"))

# This works for some reason
client.delete_file(project.id, "dummy.txt")
```

**Comment by artmoskvin** [comment]
Hmm I can't reproduce the problem with the images I have. I checked the `/workspace` folder and in my case it was owned by root:
<img width="401" alt="image" src="https://github.com/user-attachments/assets/afe24adf-7340-468a-a193-3d08fdee6e25">

I also followed the steps above (creating an dummy file and updating its content) and it works.

Is there any way you could share your image or Dockerfile with me?

**Comment by prabhuteja12** [comment]
```python
    hc = HideClient()
    project = hc.create_project(
        repository=model.Repository(
            url="https://github.com/astropy/astropy/",
        ),
        devcontainer=ImageDevContainer(
            image="continuumio/miniconda3"
        ),
        languages=[Language.PYTHON],
    )
    print(hc.run_task(project.id, "ls -l").stdout)
```

prints

```
-rw-r--r--  1 24909395 users 619130 Nov  7 21:20 CHANGES.rst
-rw-r--r--  1 24909395 users     66 Nov  7 21:20 CITATION
-rw-r--r--  1 24909395 users  69267 Nov  7 21:20 CITATION.cff
...
```

**Comment by prabhuteja12** [comment]
@artmoskvin are you able to reproduce this?

**Comment by artmoskvin** [comment]
@prabhuteja12 Nope and I'm trying to understand why. Do you run this on Linux? Do you run Docker as non-root?
<img width="520" alt="image" src="https://github.com/user-attachments/assets/353515e1-47a0-4945-95b9-6705050a06b8">

**Comment by artmoskvin** [comment]
Also, checked the Dockerfile for miniconda3 and it doesn't contain any `USER` instructions which means the behaviour you see is coming from Docker host. Regardless, I'm gonna try to find a Linux machine and try to reproduce the problem there.

**Comment by prabhuteja12** [comment]
Indeed, I'm running on Linux.

**Comment by artmoskvin** [comment]
@prabhuteja12 one more thing. Could you please run Hide with the debug flag `hide run --debug`, create the project and check the directory where the project is created? In the debug logs, you should see something like `Created project directory: ...`. Could you check the owner of that directory and its content?

**Comment by prabhuteja12** [comment]
All hide projects in my `~/.hide/projects` are owned by my user.

**Comment by prabhuteja12** [comment]
So running `id -u ${USER}` on my linux gives me the `24909395` code I reported above. So I assume docker is running as my local user.  Is it expected to run as `root` so the ownership is set like that?

**Comment by artmoskvin** [comment]
Ok, turned out the volume ownership works differently on mac and linux. Asked Claude to summarize my learnings:

> On macOS, Docker runs in a VM (using the Docker Desktop hypervisor) because Docker requires Linux kernel features. This changes how volume mounting works:
> 
> 1. On Linux:
> 
> - Direct mounting between host and container
> - UIDs/GIDs are preserved
> - Files keep their original ownership
> - New files are owned by the container's user
> 
> 2. On macOS:
> 
> - Files are mounted through the VM layer (osxfs on older versions, gRPC FUSE on newer)
> - By default, files appear to be owned by root (UID 0) inside the container
> - This is a known limitation of the virtualization layer used by Docker Desktop
> - Can cause permission issues that don't exist on Linux

**Comment by artmoskvin** [comment]
@prabhuteja12 have you tried setting `containerUser="24909395"`?

**Comment by prabhuteja12** [comment]
`containerUser=str(os.getuid())` seems to work in general. 

I tested this with:

```python
hc = HideClient()
project = hc.create_project(
    repository=model.Repository(
        url="https://github.com/astropy/astropy/",
    ),
    devcontainer=ImageDevContainer(
        image="continuumio/miniconda3",
        containerUser=str(os.getuid()),
    ),
    languages=[Language.PYTHON],
)
toolkit = HideCommunicatorToolkit(project, hc)
toolkit.run_task("git config --global --add safe.directory /workspace")

print(toolkit.run_task("rm setup.py"))
print("---" * 20)
print(toolkit.run_task("git stash"))
print("---" * 20)
print(toolkit.replace_lines("setup.py", 1, 2, "import numpy as np"))```

Without that user setting, it fails.

**Comment by artmoskvin** [comment]
I was also able to reproduce the issue on Ubuntu and I confirm that `containerUser=str(os.getuid())` solves the issue. I tried different Docker settings and wanted to summarize my current understanding:
- By default, the Docker daemon runs as the root user, also known as "root" mode.
- To reach Docker running in "root" mode, users can either run commands (e.g. `docker run`, `hide run`) with sudo or join the group `docker` that grants access to Docker without sudo.
- In "root" mode, UIDs/GIDs are preserved, mounted files keep their original ownership but new files are owned by the container's user.
- There's also "rootless" mode that allows running the Docker daemon and containers as a non-root user. See https://docs.docker.com/engine/security/rootless/
- In rootless mode, user ID mapping happens automatically by Docker daemon. The host user ID is mapped to UID 0 (root) inside the container which means that inside containers, ownership appears as root (UID 0) but the actual files on disk use the host user ID.
- With Docker running in rootless mode, there's no need for `containerUser=str(os.getuid())`

Hope this helps.

**Comment by prabhuteja12** [comment]
Great! Thank you. 

I think its reasonable to assume that `containerUser=str(os.getuid())` is the simplest option for most people, definitely for me. 

I'll close this issue for now.
