### ISSUE TITLE
`run_task` with timeout

### ISSUE THREAD

**Issue by wistuba** [hide-org/hide#150]
Hey, I am exposing bash to the LLM and in some cases it manages to cook up something that runs forever. Is there a way to let `run_task` time out? Right now, I'll add manually `timeout XX` in front of each command but this surfaces when the command is incorrect and crashes.

**Comment by wistuba** [comment]
I was thinking of latter where a `timeout` parameter for `run_task` would be sufficient.

**Comment by aleh-null** [comment]
Great feature request. We've done some work today and things are looking good. We just need to check that resources are released correctly on time out on the server side. Are there any other endpoint where you think timeouts from the client side would be good? 

SDK implementation https://github.com/hide-org/hide-sdk/pull/26

**Comment by wistuba** [comment]
Thanks for your efforts! I can't think of any additional time outs right now.

**Comment by aleh-null** [comment]
We've merged both PRs. Please take a look.

**Comment by wistuba** [comment]
Thanks a lot, it seems to work! It seems that on timeout the output streams are not accessible. Is this something that could be changed?

**Comment by artmoskvin** [comment]
@wistuba do you mean they are empty?

**Comment by wistuba** [comment]
I receive exit code 124, but otherwise the output streams seem empty. I had a relatively short time out when testing, maybe the stream wasn't flushed? I can check again

**Comment by wistuba** [comment]
Sorry for the late response. I can confirm that the output is available (given it was flushed already)
